// <auto-generated />
using DHSHOP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace logintest.Migrations.ImageDb
{
    [DbContext(typeof(ImageDbContext))]
    [Migration("20221127151736_DHCART")]
    partial class DHCART
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("logintest.Areas.Identity.Data.ImageModel", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ProductDetail")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ProductGPU")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("ProductPOWER")
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<string>("ProductRam")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductSize")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductSlot")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Series")
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("ProductId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("logintest.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<string>("VGAId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageProductId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("imageProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("logintest.Models.CartItem", b =>
                {
                    b.HasOne("logintest.Areas.Identity.Data.ImageModel", "image")
                        .WithMany()
                        .HasForeignKey("imageProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
